[package]
name = "auth-gatekeeper"
version = "0.1.0"
authors = ["rhangai <hangai.renan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
tokio = { version = "0.2", features = ["full"] }
ring = "0.16.15"