FROM rust:1.44 as builder
WORKDIR /opt/auth-gatekeeper
ADD ./Cargo.toml ./Cargo.lock /opt/auth-gatekeeper/
RUN cargo fetch --locked && \
	mkdir -p src && \
	echo "fn main() {}" > src/main.rs && \
	cargo build --release
ADD ./src /opt/auth-gatekeeper/src
RUN cargo build --release

FROM nginx
RUN apt-get update && \ 
	apt-get install -y curl supervisor && \
	rm -rf /var/lib/apt/lists/*

COPY ./docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./docker/auth-gatekeeper etc/nginx/auth-gatekeeper
COPY --from=builder /opt/auth-gatekeeper/target/release/auth-gatekeeper /opt/auth-gatekeeper/auth-gatekeeper

ENV AUTH_GATEKEEPER_LISTEN=unix:/var/run/auth-gatekeeper.sock,http://0.0.0.0:8088
CMD ["/usr/bin/supervisord", "-n"]
