FROM rust:1.44 as builder
WORKDIR /opt/auth-gatekeeper
ADD ./Cargo.toml ./Cargo.lock /opt/auth-gatekeeper/
RUN cargo fetch --locked && \
	mkdir -p src && \
	echo "fn main() {}" > src/main.rs && \
	cargo build --release
ADD ./src /opt/auth-gatekeeper/src
RUN cargo build --release

FROM nginx
RUN apt-get update && \ 
	apt-get install -y curl supervisor && \
	rm -rf /var/lib/apt/lists/*

COPY ./docker/nginx/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./docker/nginx/upstream.conf /etc/nginx/conf.d/auth-gatekeeper-upstrea.conf
COPY ./docker/nginx/auth-gatekeeper /etc/nginx/auth-gatekeeper
COPY --from=builder /opt/auth-gatekeeper/target/release/auth-gatekeeper /opt/auth-gatekeeper/auth-gatekeeper

RUN mkdir -p /var/run/auth-gatekeeper && chown nginx:nginx /var/run/auth-gatekeeper
ENV AUTH_GATEKEEPER_LISTEN=unix:/var/run/auth-gatekeeper/server.sock
CMD ["/usr/bin/supervisord", "-n"]
