FROM rust:1.44 as builder
WORKDIR /opt/auth-gatekeeper
ADD ./Cargo.toml ./Cargo.lock /opt/auth-gatekeeper/
RUN cargo fetch --locked && \
	mkdir -p src && \
	echo "fn main() {}" > src/main.rs && \
	cargo build --release

ADD ./src /opt/auth-gatekeeper/src
RUN touch -a -m src/main.rs && cargo build --release

FROM traefik as traefik

FROM debian:buster-slim
RUN apt-get update && \ 
	apt-get install -y curl supervisor && \
	rm -rf /var/lib/apt/lists/* && \
	mkdir -p /etc/traefik /etc/traefik/providers

COPY --from=traefik /usr/local/bin/traefik /usr/local/bin/traefik
COPY ./docker/traefik/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./docker/traefik/traefik.toml /etc/traefik/traefik.toml
COPY ./docker/traefik/auth.toml /etc/traefik/providers/auth.toml
COPY --from=builder /opt/auth-gatekeeper/target/release/auth-gatekeeper /opt/auth-gatekeeper/auth-gatekeeper

RUN mkdir -p /var/run/auth-gatekeeper
ENV AUTH_GATEKEEPER_LISTEN=http://127.0.0.1:8088/

COPY ./docker/traefik/docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/bin/supervisord", "-n"]
EXPOSE 80