[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.ping]
    address = ":8888"

[ping]
  entryPoint = "ping"
  
[api]
  dashboard = true
  insecure = true

[providers.file]
  directory = "/etc/traefik/providers"

[log]
  level = "DEBUG"